// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurpleBuzz.Data;

#nullable disable

namespace PurpleBuzz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PurpleBuzz.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundImage = "banner-img-02.svg",
                            Description = "Vector illustration credit goes to <a rel=\"nofollow\" href=\"http://freepik.com/\" target=\"_blank\">FreePik</a> website. Purple Buzz is provided by TemplateMo. Lorem ipsum dolor sit amet, consectetur.",
                            SoftDelete = false,
                            Title = "About Us"
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Filter = "graphic",
                            Name = "Graphics",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            Filter = "ui",
                            Name = "UI/UX",
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            Filter = "branding",
                            Name = "Branding",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundImage = "banner-img-01.svg",
                            Description = "Vector illustration is from <a rel=\"nofollow\" href=\"https://storyset.com/\" target=\"_blank\">StorySet</a>. Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.",
                            SoftDelete = false,
                            Subtitle = "Elit, sed do eiusmod tempor",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "5 Users",
                            PackageId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "2 TB Space",
                            PackageId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "Community Forums",
                            PackageId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            Description = "Email Support",
                            PackageId = 1,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            Description = "25 to 99 Users",
                            PackageId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            Description = "10 TB space",
                            PackageId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            Description = "Source Files",
                            PackageId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            Description = "Live Chat",
                            PackageId = 2,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            Description = "100 users or more",
                            PackageId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 10,
                            Description = "80 TB space",
                            PackageId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 11,
                            Description = "Full Access Sources",
                            PackageId = 3,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 12,
                            Description = "Customizations",
                            PackageId = 3,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonOutline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "white",
                            ButtonOutline = "primary",
                            CardHeight = "pb-5 mt-5",
                            IconColor = "text-secondary",
                            Name = "Free Plan",
                            Price = 0m,
                            SoftDelete = false,
                            TextColor = "black"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColor = "bg-secondary",
                            ButtonOutline = "light",
                            CardHeight = "pt-3",
                            IconColor = "text-white",
                            Name = "Standart Plan",
                            Price = 120m,
                            SoftDelete = false,
                            TextColor = "text-white"
                        },
                        new
                        {
                            Id = 3,
                            BackgroundColor = "white",
                            ButtonOutline = "primary",
                            CardHeight = "pb-5 mt-5",
                            IconColor = "text-secondary",
                            Name = "Enterprise",
                            Price = 840m,
                            SoftDelete = false,
                            TextColor = "black"
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "You are free to use this template for your commercial or business websites. You are not allowed to re-distribute this template ZIP file on any template collection websites. It is too easy to illegally copy and repost this template.",
                            SoftDelete = false,
                            Title = "Make Success for future"
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Purple Buzz is a corporate HTML template with Bootstrap 5 Beta 1. This CSS template is 100% free to download provided by <a rel=\"nofollow\" href=\"https://templatemo.com/page/1\" target=\"_parent\">TemplateMo</a>. Total 6 HTML pages included in this template. Icon fonts by <a rel=\"nofollow\" href=\"https://boxicons.com/\" target=\"_blank\">Boxicons</a>. Photos are from <a rel=\"nofollow\" href=\"https://unsplash.com/\" target=\"_blank\">Unsplash</a> and <a rel=\"nofollow\" href=\"https://icons8.com/\" target=\"_blank\">Icons 8</a>.",
                            IsActive = "active",
                            SoftDelete = false,
                            Title = "Develop <strong>Strategies</strong> for <br>your business"
                        },
                        new
                        {
                            Id = 2,
                            Description = "You are not allowed to re-distribute this Purple Buzz HTML template as a downloadable ZIP file on any kind of Free CSS collection websites. This is strongly prohibited. Please contact TemplateMo for more information.",
                            IsActive = "deactive",
                            SoftDelete = false,
                            Title = "HTML CSS Template with Bootstrap 5 Beta 1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat.",
                            IsActive = "deactive",
                            SoftDelete = false,
                            Title = "Cupidatat non proident, sunt in culpa qui officia"
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.SliderBackground", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SliderBackgrounds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "banner-bg-01.jpg",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postiton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe",
                            Image = "team-01.jpg",
                            Postiton = "Business Development",
                            SoftDelete = false,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Jane Doe",
                            Image = "team-02.jpg",
                            Postiton = "Media Development",
                            SoftDelete = false,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sam",
                            Image = "team-03.jpg",
                            Postiton = "Developer",
                            SoftDelete = false,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRecent")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            IsRecent = false,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Ullamco laboris nisi ut aliquip ex",
                            IsRecent = true,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Psum officia anim id est laborum.",
                            IsRecent = true,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Sum dolor sit consencutur",
                            IsRecent = true,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet",
                            IsRecent = true,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Put enim ad minim veniam",
                            IsRecent = true,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Mollit anim id est laborum.",
                            IsRecent = true,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.WorkImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("WorkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("WorkImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            Name = "services-01.jpg",
                            SoftDelete = false,
                            WorkId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            Name = "services-06.jpg",
                            SoftDelete = false,
                            WorkId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsMain = true,
                            Name = "services-02.jpg",
                            SoftDelete = false,
                            WorkId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsMain = false,
                            Name = "services-04.jpg",
                            SoftDelete = false,
                            WorkId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsMain = true,
                            Name = "services-03.jpg",
                            SoftDelete = false,
                            WorkId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            Name = "services-01.jpg",
                            SoftDelete = false,
                            WorkId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsMain = true,
                            Name = "services-04.jpg",
                            SoftDelete = false,
                            WorkId = 4
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            Name = "services-08.jpg",
                            SoftDelete = false,
                            WorkId = 4
                        },
                        new
                        {
                            Id = 9,
                            IsMain = true,
                            Name = "services-05.jpg",
                            SoftDelete = false,
                            WorkId = 5
                        },
                        new
                        {
                            Id = 10,
                            IsMain = false,
                            Name = "services-02.jpg",
                            SoftDelete = false,
                            WorkId = 5
                        },
                        new
                        {
                            Id = 11,
                            IsMain = true,
                            Name = "services-06.jpg",
                            SoftDelete = false,
                            WorkId = 6
                        },
                        new
                        {
                            Id = 12,
                            IsMain = false,
                            Name = "services-08.jpg",
                            SoftDelete = false,
                            WorkId = 6
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            Name = "services-07.jpg",
                            SoftDelete = false,
                            WorkId = 7
                        },
                        new
                        {
                            Id = 14,
                            IsMain = false,
                            Name = "services-03.jpg",
                            SoftDelete = false,
                            WorkId = 7
                        },
                        new
                        {
                            Id = 15,
                            IsMain = true,
                            Name = "services-08.jpg",
                            SoftDelete = false,
                            WorkId = 8
                        },
                        new
                        {
                            Id = 16,
                            IsMain = false,
                            Name = "services-05.jpg",
                            SoftDelete = false,
                            WorkId = 8
                        },
                        new
                        {
                            Id = 17,
                            IsMain = true,
                            Name = "recent-work-01.jpg",
                            SoftDelete = false,
                            WorkId = 9
                        },
                        new
                        {
                            Id = 18,
                            IsMain = false,
                            Name = "recent-work-03.jpg",
                            SoftDelete = false,
                            WorkId = 9
                        },
                        new
                        {
                            Id = 19,
                            IsMain = true,
                            Name = "recent-work-02.jpg",
                            SoftDelete = false,
                            WorkId = 10
                        },
                        new
                        {
                            Id = 20,
                            IsMain = false,
                            Name = "recent-work-01.jpg",
                            SoftDelete = false,
                            WorkId = 10
                        },
                        new
                        {
                            Id = 21,
                            IsMain = true,
                            Name = "recent-work-03.jpg",
                            SoftDelete = false,
                            WorkId = 11
                        },
                        new
                        {
                            Id = 22,
                            IsMain = false,
                            Name = "recent-work-05.jpg",
                            SoftDelete = false,
                            WorkId = 11
                        },
                        new
                        {
                            Id = 23,
                            IsMain = true,
                            Name = "recent-work-04.jpg",
                            SoftDelete = false,
                            WorkId = 12
                        },
                        new
                        {
                            Id = 24,
                            IsMain = false,
                            Name = "recent-work-02.jpg",
                            SoftDelete = false,
                            WorkId = 12
                        },
                        new
                        {
                            Id = 25,
                            IsMain = true,
                            Name = "recent-work-05.jpg",
                            SoftDelete = false,
                            WorkId = 13
                        },
                        new
                        {
                            Id = 26,
                            IsMain = false,
                            Name = "recent-work-03.jpg",
                            SoftDelete = false,
                            WorkId = 13
                        },
                        new
                        {
                            Id = 27,
                            IsMain = true,
                            Name = "recent-work-06.jpg",
                            SoftDelete = false,
                            WorkId = 14
                        },
                        new
                        {
                            Id = 28,
                            IsMain = false,
                            Name = "recent-work-01.jpg",
                            SoftDelete = false,
                            WorkId = 14
                        });
                });

            modelBuilder.Entity("PurpleBuzz.Models.Offer", b =>
                {
                    b.HasOne("PurpleBuzz.Models.Package", "Package")
                        .WithMany("Offers")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PurpleBuzz.Models.TeamMember", b =>
                {
                    b.HasOne("PurpleBuzz.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PurpleBuzz.Models.Work", b =>
                {
                    b.HasOne("PurpleBuzz.Models.Category", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PurpleBuzz.Models.WorkImage", b =>
                {
                    b.HasOne("PurpleBuzz.Models.Work", "Work")
                        .WithMany("WorkImages")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("PurpleBuzz.Models.Category", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("PurpleBuzz.Models.Package", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PurpleBuzz.Models.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("PurpleBuzz.Models.Work", b =>
                {
                    b.Navigation("WorkImages");
                });
#pragma warning restore 612, 618
        }
    }
}
